import Link from "next/link";
import "./globals.css";
import Control from "./Control";

// db.json에 명령어
// npx json-server --port 9999 --watch bd.json

export const metadata = {
  title: "Next.js study",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // 동기적으로 바꾼다.
  const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/topics`, {
    // 0초 동안만 캐시를 유지하겠다는 뜻
    // next: { revalidate: 0 }
    // 캐시를 저장하지 않겠다는 뜻
    cache: "no-store",
  });
  const topics = await response.json();
  // nextjs는 한 번 가져온 정보를 저장해 둔다.

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic) => (
            <li key={topic.id}>
              <Link href={`/read/${topic.id}`}>{topic.title}</Link>
            </li>
          ))}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
