import Link from "next/link";
import "./globals.css";

// db.json에 명령어
// npx json-server --port 9999 --watch bd.json

export const metadata = {
  title: "Next.js study",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // 동기적으로 바꾼다.
  const response = await fetch("http://localhost:9999/topics");
  const topics = await response.json();

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic) => (
            <li key={topic.id}>
              <Link href={`/read/${topic.id}`}>{topic.title}</Link>
            </li>
          ))}
        </ol>
        {children}
        <ol>
          <li>
            <a href="/create">Create</a>
          </li>
          <li>
            <a href="/update/1">Update</a>
          </li>
          <li>
            <input type="button" value="delete" />
          </li>
        </ol>
      </body>
    </html>
  );
}
