"use client"; // 클라이언트 컴포넌트를 사용하려면 반드시 이 표시가 있어야 한다.
import { useEffect, useState } from "react";
import Link from "next/link";
import "./globals.css";

// meta는 서버컴포넌트에서만 쓸 수 있다.
// export const metadata = {
//   title: "Next.js study",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [topics, setTopics] = useState([]);

  useEffect(() => {
    fetch("http://localhost:9999/topics")
      .then((res) => res.json())
      .then((res) => setTopics(res));
  }, []);

  // console.log("topics:", topics);

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic) => (
            <li key={topic.id}>
              <Link href={`/read/${topic.id}`}>{topic.title}</Link>
            </li>
          ))}
        </ol>
        {children}
        <ol>
          <li>
            <a href="/create">Create</a>
          </li>
          <li>
            <a href="/update/1">Update</a>
          </li>
          <li>
            <input type="button" value="delete" />
          </li>
        </ol>
      </body>
    </html>
  );
}
